
obj-$(CONFIG_COMCERTO_TEST_ZDS_SLIC) += vp880_abs_calibration.o vp880_calibration_common.o vp880_control_common.o vp880_fxs_control.o vp880_init.o vp880_linestate_control.o vp880_lp_control.o vp880_query.o vp880_seq.o vp880_tracker_calibration.o

