obj-$(CONFIG_COMCERTO_TEST_MSIF_SLIC) += proslic.o proslic_tstin.o \
	si3226_patch_05072008.o si3226_intf.o si3226_patch_05072008.o \
		si3226_patch_08112008.o si3226x_intf.o si_voice.o si_voice_version.o

