# Object file lists.

CPPFLAGS       += -L$(LINUXINCLUDE)

obj-$(CONFIG_COMCERTO_TEST) += tests.o run.o dump.o
obj-$(CONFIG_COMCERTO_TEST_DDR) += test_ddr.o
obj-$(CONFIG_COMCERTO_TEST_PFE) += test_pfe.o
obj-$(CONFIG_COMCERTO_TEST_TZ) += test_tz.o tz/
obj-$(CONFIG_COMCERTO_TEST_L2CC) += test_l2cc.o
obj-$(CONFIG_COMCERTO_TEST_DECT) += test_dect.o dect/
obj-$(CONFIG_COMCERTO_TEST_DUALCORE) += test_dualcore.o
obj-$(CONFIG_COMCERTO_TEST_PCIE) += test_pcie.o
obj-$(CONFIG_COMCERTO_TEST_FUART) += test_fastuart.o
obj-$(CONFIG_COMCERTO_TEST_NOR) += test_nor.o
obj-$(CONFIG_COMCERTO_DIAG_UTILPE_IPSEC) += test_util_ipsec.o
obj-$(CONFIG_COMCERTO_TEST_SPI) += test_spi.o
obj-$(CONFIG_COMCERTO_TEST_ZDSTDM) += zds_data.o test_zdstdm.o
obj-$(CONFIG_COMCERTO_TEST_ZDS_SLIC) += legerity/ test_zds_slic.o
obj-$(CONFIG_COMCERTO_TEST_MSIF_TDM) += msif_data.o test_msif_tdm.o
obj-$(CONFIG_COMCERTO_TEST_MSIF_SLIC) += proslic/ test_msif_slic.o
obj-$(CONFIG_COMCERTO_TEST_I2C) += test_i2c.o
obj-$(CONFIG_COMCERTO_TEST_OTP) += test_otp.o
obj-$(CONFIG_COMCERTO_TEST_USB3) += test_usb3.o
obj-$(CONFIG_COMCERTO_TEST_NAND_ECC) += test_nand_ecc.o
obj-$(CONFIG_COMCERTO_TEST_SATA) += test_sata.o
