#LIB     := $(obj)liblegerity.a

obj-$(CONFIG_COMCERTO_TEST_ZDS_SLIC) += profiles8-le88264_abs_zsi.o legerity_event_hdlr.o legerity_main.o api-II/
#\
#	api-II/api_lib/common/vp_api_common.o \
#	api-II/api_lib/common/vp_api_config.o \
#	api-II/api_lib/common/vp_api_control.o \
#	api-II/api_lib/common/vp_api_cslac_seq.o \
#	api-II/api_lib/common/vp_api_init.o \
#	api-II/api_lib/common/vp_api_query.o \
#	api-II/api_lib/vp880_api/vp880_abs_calibration.o \
#	api-II/api_lib/vp880_api/vp880_calibration_common.o \
#	api-II/api_lib/vp880_api/vp880_control_common.o \
#	api-II/api_lib/vp880_api/vp880_fxs_control.o \
#	api-II/api_lib/vp880_api/vp880_init.o \
#	api-II/api_lib/vp880_api/vp880_linestate_control.o \
#	api-II/api_lib/vp880_api/vp880_lp_control.o \
#	api-II/api_lib/vp880_api/vp880_query.o \
#	api-II/api_lib/vp880_api/vp880_seq.o \
#	api-II/api_lib/vp880_api/vp880_tracker_calibration.o \
#	api-II/arch/uvb/sys_service.o \
#	profiles8-ve8820-invert-boost.o \
#	api-II/arch/uvb/vp_hal.o \
#	legerity_event_hdlr.o legerity_main.o

